[package]
name = "teaty"
version = "0.1.0"
authors = ["ankit <sahuankit.murhu@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
rand = "0.9.0"
